### ISSUE TITLE
Received a 500 error when saving a large file to fedora

### ISSUE THREAD

**Issue by cam156** [fcrepo4/fcrepo4#696] opened 2015-01-26 17:05 UTC
I was sending a 7GB file to fedora and received the error below.  I was not able to repeat the failure unfortunately...

```
 #<Ldp::HttpError: STATUS: 500 javax.jcr.ItemExistsException: A node definition that allows same name siblings could not be found for the node "{}content" in workspace "default"
        at org.modeshape.jcr.JcrSession$JcrPreSave.processAfterLocking(JcrSession.java:2422)
        at org.modeshape.jcr.cache.document.WritableSessionCache.runPreSaveAfterLocking(WritableSessionCache.java:530)
        at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:591)
        at org.modeshape.jcr.JcrSession.save(JcrSession.java:1165)
        at org.fcrepo.http.api.FedoraLdp.createOrReplaceObjectRdf(FedoraLdp.java:295)
        at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMeth...>
```

**Comment by awoods** [comment] 2015-01-26 17:58
It looks like you tried to make the identical request twice, hence the "ItemExistsException". Which HTTP method did you use? POST? PUT?

**Comment by jcoyne** [comment] 2015-01-26 18:37
@awoods should that be a 500 error?

**Comment by awoods** [comment] 2015-01-26 19:51
Agreed, should probably be a 409 Conflict. But when I try to reproduce the issue I do get a 409. Can you provide any more detail on what actions were performed? If not, I will go ahead and close this ticket as: "Can not reproduce"

**Comment by acoburn** [comment] 2016-10-07 00:44
Closing this as "Cannot reproduce"

**Closed by acoburn** 2016-10-07 00:44 UTC
