### ISSUE TITLE
Missing subresource label.

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#972] opened 2016-01-28 18:29 UTC
There is no text within the `h3.panel-title > a` see:
In Fcrepo 4.4.0

```html
            <h2>Other Resources</h2>
            <div class="panel-group" id="accordion">
                                                <div class="panel panel-default" resource="http://localhost:8983/fedora/rest/test/cv/43/nw/81/cv43nw81s#timespan_g70254963944300">
                        <div class="panel-heading collapsed" data-toggle="collapse" data-target="#http_localhost_8983_fedora_rest_test_cv_43_nw_81_cv43nw81s_timespan_g70254963944300_triples" >
                                                            <h3 class="ctitle panel-title"><a href="http://localhost:8983/fedora/rest/test/cv/43/nw/81/cv43nw81s#timespan_g70254963944300"></a></h3>
                                                    </div>
                        <div class="panel-collapse collapse"  id="http_localhost_8983_fedora_rest_test_cv_43_nw_81_cv43nw81s_timespan_g70254963944300_triples">
                            <div class="panel-body">
                                        <dl>
```

<img width="872" alt="screen shot 2016-01-28 at 12 29 39 pm" src="https://cloud.githubusercontent.com/assets/92044/12654693/e2384d94-c5ba-11e5-88f1-a51d26b39d12.png">

**Comment by jcoyne** [comment] 2016-01-29 18:04
I get the same behavior in 4.5.0

**Comment by acoburn** [comment] 2016-01-29 18:12
Could you please provide the underlying RDF for the resource in question.

**Comment by jcoyne** [comment] 2016-01-29 20:28
I had already erased that existing data, now I'm unable to duplicate it.

**Comment by acoburn** [comment] 2016-10-07 00:03
@jcoyne I'm going to close this because the templating code has been reworked since v4.5.0, and I am not able to reproduce the issue in the current released version of Fedora. If you encounter the issue again, please re-open the issue.

**Closed by acoburn** 2016-10-07 00:03 UTC
