### ISSUE TITLE
Stack trace (ItemExistsException) in a new repo

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#880] opened 2015-08-10 15:25 UTC
When I have a brand new repo (Fcrepo 4.2), I get this error on the first PUT:
```
HTTP PUT (63.99ms) http://127.0.0.1:8983/fedora/rest/dev/f3/n0/14/n7/f3n014n7 
Request body 
<http://127.0.0.1:8983/fedora/rest/dev/f3/n0/14/n7/f3n014n7> <http://purl.org/dc/terms/title> "Examining Intra- and Interpersonal Variables Involved in Neuropsychological and Personality Assessment: Are Asian Americans the \"Model Examinees\"?";
   <http://bibframe.org/vocab/dissertationDegree> "Ph.D.";
   <http://bibframe.org/vocab/dissertationInstitution> "University of California, Santa Barbara";
   <http://bibframe.org/vocab/dissertationYear> "2011";
   <http://bibframe.org/vocab/otherEdition> "http://gateway.proquest.com/openurl?url_ver=Z39.88-2004&rft_val_fmt=info:ofi/fmt:kev:mtx:dissertation&res_dat=xri:pqm&rft_dat=xri:pqdiss:3481953";
   <http://id.loc.gov/vocabulary/identifiers/isbn> "9781267019691";
   <http://id.loc.gov/vocabulary/relators/aut> "Chang, Jenss";
   <http://id.loc.gov/vocabulary/relators/dgg> "University of California, Santa Barbara. Counseling, Clinical & School Psychology";
   <http://id.loc.gov/vocabulary/relators/dgs> "Steve R. Smith";
   <http://id.loc.gov/vocabulary/relators/pup> "Santa Barbara, Calif.";
   <http://projecthydra.org/ns/relations#isGovernedBy> <http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted>;
   <http://purl.org/dc/terms/description> "The present project investigated the role of ethnicity, Asian American (AA) cultural immersion level, and examiner-examinee racial match on commonly-used neuropsychological and personality measures (Studies One and Two, respectively). As hypothesized, culturally-different responding occurred between European Americans (EAs) and AAs on neuropsychology and personality tests. Specifically, AAs received higher scores on the Rey-Osterrieth Complex Figure (ROCF) and Developmental Test of Visual Perception - Adult and Adolescent Version (DTVP-A) variables. Contrary to prediction, AAs also scored higher on efficiency-related neuropsychological variables, indicating that they were able to simultaneously exercise fastidiousness and efficiency for these tasks. Results also revealed that AAs and EAs responded differently on the Personality Assessment Inventory (PAI) and the Rorschach Inkblot Method.",
     "AAs endorsed more items related to anxiety, paranoia, and anxiety-related disorders on the PAI and provided more unconventional, Aggressive Content (AgC), and Cooperative Movement (COP) responses on the Rorschach. ANOVAs and Fisher's Least Square Differences (LSD) revealed that AA cultural immersion groups generally did not respond differently from one another on neuropsychological or personality tests. One exception was on the inanimate movement ( m) variable on the Rorschach, which suggested that more acculturated AAs experienced more situational anxiety while completing the task than enculturated, bicultural, and marginalized AAs. Last, examiner-examinee racial dis/similarity did not play a significant role in assessment as it does in psychotherapy settings. These studies propose that the neuropsychological and personality tests under investigation can be used with AA groups of varying cultural immersion statuses.",
     "Because the samples used in this project were limited to college-aged AA adults from the West Coast with a higher concentration of Chinese Americans and females, the results do not generalize to the broader AA population in the U.S. Future research should attempt to replicate these results with more diverse groups of AAs, including AAs of differing ages, education levels, geographical regions, genders, and socioeconomic statuses. On the whole, these results call for a more thoughtful and critical analysis from practitioners and researchers in order to promote the cultural sensitivity of the field.";
   <http://purl.org/dc/terms/extent> "1 online resource (168 pages)";
   <http://purl.org/dc/terms/identifier> "ark:/48907/f3n014n7";
   <http://purl.org/dc/terms/issued> "2011";
   <http://purl.org/dc/terms/language> "English";
   <http://purl.org/dc/terms/publisher> "University of California, Santa Barbara";
   <http://www.loc.gov/mods/rdf/v1#recordIdentifier> "003683909";
   <info:fedora/fedora-system:def/model#hasModel> "ETD" .

  Response status Net::HTTPInternalServerError (500)
Response body javax.jcr.ItemExistsException: A node definition that allows same name siblings could not be found for the node "{}f3" in workspace "default"
	at org.modeshape.jcr.JcrSession$JcrPreSave.processAfterLocking(JcrSession.java:2422)
	at org.modeshape.jcr.cache.document.WritableSessionCache.runPreSaveAfterLocking(WritableSessionCache.java:541)
	at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:614)
	at org.modeshape.jcr.JcrSession.save(JcrSession.java:1166)
	at org.fcrepo.http.api.FedoraLdp.createOrReplaceObjectRdf(FedoraLdp.java:309)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by awoods** [comment] 2015-08-10 15:41
Unable to reproduce.

**Comment by jcoyne** [comment] 2015-08-10 15:50
I've produced it on several machines and can do so dependably. Is there anything else I can give you?

**Comment by jcoyne** [comment] 2015-08-10 16:43
@awoods what is `"{}f3"`? I've not seen that before.

**Comment by ajs6f** [comment] 2015-08-10 16:44
Looks like a node named `f3` with no namespace to the name. Look at the pairtree you're punching.

**Comment by awoods** [comment] 2015-08-10 16:50
If you have reproduced the error using `curl`, that command would be helpful (`curl -i -XPUT --data-binary @body.rdf -H"Content-Type: text/turtle" localhost:8080/rest/dev/f3/n0/14/n7/f3n014n7` succeeds locally, with updated [body.rdf](https://gist.github.com/awoods/83c4ce4ab6a5624485ab) ), and any updates you may have made to the F4 configuration, I will certainly try to produce the error again on my side.
I notice that the following resource must have already been created: `http://localhost:8080/rest/dev/authorities/policies/restricted` ...which makes me assume this is not a purely clean repository.
Does `f3` already exist?

**Comment by jcoyne** [comment] 2015-08-10 17:47
Here's a full log of what I'm doing.  I wonder if this could be a concurrency issue?
```
D, [2015-08-10T12:37:53.391694 #88186] DEBUG -- : HTTP PUT (8.48ms)  http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted
D, [2015-08-10T12:37:53.391779 #88186] DEBUG -- : Request body  
<http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted> <http://purl.org/dc/terms/title> "Restricted access";
   <info:fedora/fedora-system:def/model#hasModel> "Hydra::AdminPolicy" .

D, [2015-08-10T12:37:53.391815 #88186] DEBUG -- : Response status  Net::HTTPCreated (201)
D, [2015-08-10T12:37:53.391843 #88186] DEBUG -- : Response body  http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted
D, [2015-08-10T12:37:53.438259 #88186] DEBUG -- : HTTP GET (13.74ms)  http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted
D, [2015-08-10T12:37:53.438317 #88186] DEBUG -- : Response status  Net::HTTPOK (200)
D, [2015-08-10T12:37:53.438341 #88186] DEBUG -- : Response body  @prefix premis: <http://www.loc.gov/premis/rdf/v1#> .
@prefix nt: <http://www.jcp.org/jcr/nt/1.0> .
@prefix ns020: <http://bibframe.org/vocab/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ns004: <http://projecthydra.org/ns/auth/acl#> .
@prefix ns003: <http://www.w3.org/ns/auth/acl#> .
@prefix ns002: <http://purl.org/dc/terms/> .
@prefix ns001: <info:fedora/fedora-system:def/model#> .
@prefix xsi: <http://www.w3.org/2001/XMLSchema-instance> .
@prefix ns008: <http://www.iana.org/assignments/link-relations/> .
@prefix mode: <http://www.modeshape.org/1.0> .
@prefix ns007: <http://www.openarchives.org/ore/terms/> .
@prefix ns006: <info:fedora/fedora-system:def/relations-external#> .
@prefix ns005: <http://projecthydra.org/ns/relations#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix ns009: <http://www.w3.org/2004/02/skos/core#> .
@prefix fedoraconfig: <http://fedora.info/definitions/v4/config#> .
@prefix mix: <http://www.jcp.org/jcr/mix/1.0> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix image: <http://www.modeshape.org/images/1.0> .
@prefix sv: <http://www.jcp.org/jcr/sv/1.0> .
@prefix test: <info:fedora/test/> .
@prefix ns011: <http://www.europeana.eu/schemas/edm/> .
@prefix ns010: <http://id.loc.gov/vocabulary/relators/> .
@prefix ns015: <http://www.w3.org/2003/12/exif/ns#> .
@prefix ns014: <http://www.loc.gov/mods/rdf/v1#> .
@prefix ns013: <http://opaquenamespace.org/ns/cco/> .
@prefix ns012: <http://www.cidoc-crm.org/cidoc-crm/> .
@prefix ns019: <http://id.loc.gov/vocabulary/identifiers/> .
@prefix ns018: <http://www.rdaregistry.info/Elements/u/#> .
@prefix ns017: <http://opaquenamespace.org/ns/> .
@prefix ns016: <http://www.rdaregistry.info/Elements/w/#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora: <http://fedora.info/definitions/v4/repository#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix xs: <http://www.w3.org/2001/XMLSchema> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .


<http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted> a ldp:RDFSource , ldp:Container , <http://www.jcp.org/jcr/nt/1.0folder> , <http://www.jcp.org/jcr/nt/1.0hierarchyNode> , <http://www.jcp.org/jcr/nt/1.0base> , <http://www.jcp.org/jcr/mix/1.0created> , fedora:Container , fedora:Resource , fedora:Resource , <http://www.jcp.org/jcr/mix/1.0created> , <http://www.jcp.org/jcr/mix/1.0lastModified> , <http://www.jcp.org/jcr/mix/1.0referenceable> ;
	fedora:lastModifiedBy "bypassAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:uuid "5f450df1-cbae-4ec2-bc50-6272758247d9"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:createdBy "bypassAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:primaryType "nt:folder"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:created "2015-08-10T17:37:53.39Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
	fedora:mixinTypes "fedora:Container"^^<http://www.w3.org/2001/XMLSchema#string> , "fedora:Resource"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:lastModified "2015-08-10T17:37:53.39Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
	ns001:hasModel "Hydra::AdminPolicy"^^<http://www.w3.org/2001/XMLSchema#string> ;
	ns002:title "Restricted access"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:writable "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
	fedora:hasParent <http://127.0.0.1:8983/fedora/rest/dev> .

<http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted/fcr:export?format=jcr/xml> dc:format <http://fedora.info/definitions/v4/repository#jcr/xml> .

<http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted> fedora:exportsAs <http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted/fcr:export?format=jcr/xml> .

D, [2015-08-10T12:37:53.791396 #88186] DEBUG -- : HTTP PUT (6.77ms)  http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/discovery
D, [2015-08-10T12:37:53.791472 #88186] DEBUG -- : Request body  
<http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/discovery> <http://purl.org/dc/terms/title> "Discovery access only";
   <info:fedora/fedora-system:def/model#hasModel> "Hydra::AdminPolicy" .

D, [2015-08-10T12:37:53.791496 #88186] DEBUG -- : Response status  Net::HTTPCreated (201)
D, [2015-08-10T12:37:53.791518 #88186] DEBUG -- : Response body  http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/discovery
D, [2015-08-10T12:37:53.809781 #88186] DEBUG -- : HTTP GET (6.97ms)  http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/discovery
D, [2015-08-10T12:37:53.809834 #88186] DEBUG -- : Response status  Net::HTTPOK (200)
D, [2015-08-10T12:37:53.809856 #88186] DEBUG -- : Response body  @prefix premis: <http://www.loc.gov/premis/rdf/v1#> .
@prefix nt: <http://www.jcp.org/jcr/nt/1.0> .
@prefix ns020: <http://bibframe.org/vocab/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ns004: <http://projecthydra.org/ns/auth/acl#> .
@prefix ns003: <http://www.w3.org/ns/auth/acl#> .
@prefix ns002: <http://purl.org/dc/terms/> .
@prefix ns001: <info:fedora/fedora-system:def/model#> .
@prefix xsi: <http://www.w3.org/2001/XMLSchema-instance> .
@prefix ns008: <http://www.iana.org/assignments/link-relations/> .
@prefix mode: <http://www.modeshape.org/1.0> .
@prefix ns007: <http://www.openarchives.org/ore/terms/> .
@prefix ns006: <info:fedora/fedora-system:def/relations-external#> .
@prefix ns005: <http://projecthydra.org/ns/relations#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix ns009: <http://www.w3.org/2004/02/skos/core#> .
@prefix fedoraconfig: <http://fedora.info/definitions/v4/config#> .
@prefix mix: <http://www.jcp.org/jcr/mix/1.0> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix image: <http://www.modeshape.org/images/1.0> .
@prefix sv: <http://www.jcp.org/jcr/sv/1.0> .
@prefix test: <info:fedora/test/> .
@prefix ns011: <http://www.europeana.eu/schemas/edm/> .
@prefix ns010: <http://id.loc.gov/vocabulary/relators/> .
@prefix ns015: <http://www.w3.org/2003/12/exif/ns#> .
@prefix ns014: <http://www.loc.gov/mods/rdf/v1#> .
@prefix ns013: <http://opaquenamespace.org/ns/cco/> .
@prefix ns012: <http://www.cidoc-crm.org/cidoc-crm/> .
@prefix ns019: <http://id.loc.gov/vocabulary/identifiers/> .
@prefix ns018: <http://www.rdaregistry.info/Elements/u/#> .
@prefix ns017: <http://opaquenamespace.org/ns/> .
@prefix ns016: <http://www.rdaregistry.info/Elements/w/#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora: <http://fedora.info/definitions/v4/repository#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix xs: <http://www.w3.org/2001/XMLSchema> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .


<http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/discovery> a ldp:RDFSource , ldp:Container , <http://www.jcp.org/jcr/nt/1.0folder> , <http://www.jcp.org/jcr/nt/1.0hierarchyNode> , <http://www.jcp.org/jcr/nt/1.0base> , <http://www.jcp.org/jcr/mix/1.0created> , fedora:Container , fedora:Resource , fedora:Resource , <http://www.jcp.org/jcr/mix/1.0created> , <http://www.jcp.org/jcr/mix/1.0lastModified> , <http://www.jcp.org/jcr/mix/1.0referenceable> ;
	fedora:lastModifiedBy "bypassAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:uuid "f26d6ca1-3ad0-438d-8fe9-615e0a9615e7"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:createdBy "bypassAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:primaryType "nt:folder"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:created "2015-08-10T17:37:53.79Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
	fedora:mixinTypes "fedora:Container"^^<http://www.w3.org/2001/XMLSchema#string> , "fedora:Resource"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:lastModified "2015-08-10T17:37:53.79Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
	ns001:hasModel "Hydra::AdminPolicy"^^<http://www.w3.org/2001/XMLSchema#string> ;
	ns002:title "Discovery access only"^^<http://www.w3.org/2001/XMLSchema#string> ;
	fedora:writable "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
	fedora:hasParent <http://127.0.0.1:8983/fedora/rest/dev> ;
	fedora:exportsAs <http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/discovery/fcr:export?format=jcr/xml> .

<http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/discovery/fcr:export?format=jcr/xml> dc:format <http://fedora.info/definitions/v4/repository#jcr/xml> .

D, [2015-08-10T12:37:54.156426 #88186] DEBUG -- : HTTP PUT (25.48ms)  http://127.0.0.1:8983/fedora/rest/dev/f3/n0/14/n7/f3n014n7
D, [2015-08-10T12:37:54.156685 #88186] DEBUG -- : Request body  
<http://127.0.0.1:8983/fedora/rest/dev/f3/n0/14/n7/f3n014n7> <http://projecthydra.org/ns/relations#isGovernedBy> <http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted>;
   <http://purl.org/dc/terms/identifier> "ark:/48907/f3n014n7";
   <http://www.loc.gov/mods/rdf/v1#recordIdentifier> "003683909";
   <info:fedora/fedora-system:def/model#hasModel> "ETD" .

D, [2015-08-10T12:37:54.156890 #88186] DEBUG -- : Response status  Net::HTTPCreated (201)
D, [2015-08-10T12:37:54.156975 #88186] DEBUG -- : Response body  http://127.0.0.1:8983/fedora/rest/dev/f3/n0/14/n7/f3n014n7
D, [2015-08-10T12:37:54.158936 #88186] DEBUG -- : HTTP PUT (21.20ms)  http://127.0.0.1:8983/fedora/rest/dev/f3/6q/1v/5v/f36q1v5v
D, [2015-08-10T12:37:54.160925 #88186] DEBUG -- : Request body  
<http://127.0.0.1:8983/fedora/rest/dev/f3/6q/1v/5v/f36q1v5v> <http://projecthydra.org/ns/relations#isGovernedBy> <http://127.0.0.1:8983/fedora/rest/dev/authorities/policies/restricted>;
   <http://purl.org/dc/terms/identifier> "ark:/48907/f36q1v5v";
   <http://www.loc.gov/mods/rdf/v1#recordIdentifier> "003751817";
   <info:fedora/fedora-system:def/model#hasModel> "ETD" .

D, [2015-08-10T12:37:54.161334 #88186] DEBUG -- : Response status  Net::HTTPInternalServerError (500)
D, [2015-08-10T12:37:54.161486 #88186] DEBUG -- : Response body  javax.jcr.ItemExistsException: A node definition that allows same name siblings could not be found for the node "{}f3" in workspace "default"
	at org.modeshape.jcr.JcrSession$JcrPreSave.processAfterLocking(JcrSession.java:2422)
	at org.modeshape.jcr.cache.document.WritableSessionCache.runPreSaveAfterLocking(WritableSessionCache.java:541)
	at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:614)
	at org.modeshape.jcr.JcrSession.save(JcrSession.java:1166)
	at org.fcrepo.http.api.FedoraLdp.createOrReplaceObjectRdf(FedoraLdp.java:309)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jcoyne** [comment] 2015-08-10 18:10
I've confirmed that I don't see this error if I'm running in a single thread. Seems to be a concurrency issue.

**Comment by jcoyne** [comment] 2015-08-10 18:18
Yes, definitely concurrent writes to the same non-existent parent node. This is how you do it:

```
$ curl -i -XPUT -H"Content-Type: text/turtle" --data-binary @node2.ttl http://fedoraAdmin:fedoraAdmin@localhost:8983/fedora/rest/dev/f3/6q/1v/5v/f36q1v5v & curl -i -XPUT -H"Content-Type: text/turtle" --data-binary @node1.ttl http://fedoraAdmin:fedoraAdmin@localhost:8983/fedora/rest/dev/f3/n0/14/n7/f3n014n7
[1] 88563
HTTP/1.1 201 Created
ETag: "2013fd88abefe42fea3685ca209057151d819759"
Last-Modified: Mon, 10 Aug 2015 18:17:19 GMT
Content-Length: 58
Location: http://localhost:8983/fedora/rest/dev/f3/6q/1v/5v/f36q1v5v
Content-Type: text/plain

http://localhost:8983/fedora/rest/dev/f3/6q/1v/5v/f36q1v5vHTTP/1.1 500 Internal Server Error
Content-Length: 4862
Content-Type: text/plain

javax.jcr.ItemExistsException: A node definition that allows same name siblings could not be found for the node "{}f3" in workspace "default"
	at org.modeshape.jcr.JcrSession$JcrPreSave.processAfterLocking(JcrSession.java:2422)
	at org.modeshape.jcr.cache.document.WritableSessionCache.runPreSaveAfterLocking(WritableSessionCache.java:541)
	at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:614)
```

**Comment by awoods** [comment] 2015-08-10 18:53
Two requests trying to concurrently create a resource should result in an error. Would you be satisfied with a `409 Conflict` response?

**Comment by jcoyne** [comment] 2015-08-10 19:08
A 409 would be better than a 500.  But still a little weird, because I'm trying to create f3/child1 and f3/child2 and the conflict is on f3, which I don't really want to create, but I have to due to the bug that makes containers slow if they get a lot of elements.  So, if you take your proposed approach, you're starting to offload a lot of logic that I want the server to do automatically to the client.  Basically I see the path (f3/child2) as a key, and I don't care that f3 is a container, and I don't want to have to manage it as such.

**Comment by ajs6f** [comment] 2015-08-11 17:57
I'm still confused about why we are exposing `f3` or any other part of the pairtree. Wasn't the original idea to keep that internal?

**Comment by jcoyne** [comment] 2015-08-11 18:07
ajs6f: I'm with you. I'd love for that to be internal.

**Comment by awoods** [comment] 2015-08-12 12:48
@ajs6f, @jcoyne is performing a PUT request on the path: `/rest/dev/f3/n0/14/n7/f3n014n7`. What would you expect to be "internal"?

**Comment by jcoyne** [comment] 2015-08-12 13:00
@awoods Ideally I'd just be performing a put on `/rest/dev/f3n014n7`  Its the  `f3/n0/14/n7` that could be internal and hidden from the user.

**Comment by awoods** [comment] 2015-08-12 13:17
@jcoyne, I totally get that. I was just wondering if @ajs6f had something else in mind.

**Comment by ajs6f** [comment] 2015-08-12 13:59
What @jcoyne said.

**Comment by awoods** [comment] 2015-08-16 01:09
I believe there is an issue here, but am unable to reproduce it locally. @jcoyne, do you have a script I can run to recreate the issue?

**Comment by acoburn** [comment] 2016-10-07 00:23
Closing this as it is being tracked in Jira as https://jira.duraspace.org/browse/FCREPO-2086 (there is a corresponding pull request to address this issue)

**Closed by acoburn** 2016-10-07 00:23 UTC
