### ISSUE TITLE
Certain CSS/JS assets in HTML REST endpoint eventually go 404

### ISSUE THREAD

**Issue by adolski** [fcrepo4/fcrepo4#756] opened 2015-03-27 15:49 UTC
Using Fedora 4.1.0 in Jetty, I noticed an apparent bug whereby the CSS/JS resources in the HTML REST endpoint eventually go missing (404). I don't know what causes this to happen other than that I have only noticed it after fcrepo has been running for a certain length of time (like a week) under regular use. I believe I noticed it in 4.0.0 as well. I didn't see it addressed in the Fedora 4.1.1 release notes.

Looking at the page source, the `<head>` of the interface pulls in the following assets:
- http://localhost:8080/fcrepo/rest/../static/js/jquery-1.9.1.min.js
- http://localhost:8080/fcrepo/rest/../static/js/bootstrap-3.0.0.min.js
- http://localhost:8080/fcrepo/rest/../static/css/bootstrap-3.0.0.min.css
- http://localhost:8080/fcrepo/rest/fcr:assets/common.js
- http://localhost:8080/fcrepo/rest/fcr:assets/common.css

It's only the first three that go missing. Restarting jetty fixes it. I don't see anything relevant in the log. It doesn't seem to be triggered by actually using the interface.

I am probably not giving you a lot of useful information here; let me know if there is anything I can do to help you track this down, as I seem to be able to get it to happen pretty reliably.

**Comment by awoods** [comment] 2015-03-27 15:54
Thanks, @adolski. What is your approach for reproducing this issue? start F4-jetty and let it run in the background for a week?
Can you provide the application logs?

**Comment by adolski** [comment] 2015-03-27 16:38
@awoods Pretty much. I don't know whether it's caused by some usage pattern that I inadvertently trigger roughly weekly, or the mere passage of time. If you think it would be worthwhile, I could start it up and let it sit there unused, except for checking it every few days.

I don't see anything relevant in the logs. Just a lot of `INFO 11:14:08.595 (FedoraLdp) GET resource 'xx'`and similar. Requests for these assets don't appear in the output whether missing or not.

**Comment by acoburn** [comment] 2016-10-07 00:29
@adolski have you found this issue to continue to affect Jetty deployments? Have you reproduced this issue in Fedora 4.6.0? There were some changes to how the static resources are handled in that version.

**Comment by adolski** [comment] 2016-10-07 14:48
I haven't used Fedora in some time, but more recently I had apparently the same issue -- in-JAR resources becoming unreadable over time -- in a different web app. I tracked it down to my failing to close an InputStream returned by `URL.openStream()`. I don't know if that was ever the case here, though.

**Comment by acoburn** [comment] 2016-11-04 14:50
Closing this for now as "Can't reproduce"

**Closed by acoburn** 2016-11-04 14:50 UTC
