### ISSUE TITLE
500 error.

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#694] opened 2015-01-23 15:14 UTC
When posting this graph:
```ruby
"\n<> <http://purl.org/dc/terms/description> \"\"\"\r\"\"\" .\n"
```

we get a 500 error with this stacktrace:
```
     Ldp::HttpError:
 (0x0D)STATUS: 500 org.apache.jena.riot.RiotException: [line: 2, col: 48] illegal escape sequence value:
       	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:136)
       	at org.apache.jena.riot.lang.LangEngine.raiseException(LangEngine.java:163)
       	at org.apache.jena.riot.lang.LangEngine.nextToken(LangEngine.java:106)
       	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:287)
       	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:269)
       	at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:250)
       	at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:191)
       	at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:44)
       	at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:90)
       	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:42)
       	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.ja...
```

**Comment by jcoyne** [comment] 2015-01-23 15:33
Here's a ruby script for generating that graph:
```ruby
> g = RDF::Graph.new
> g.insert([RDF::URI.new(nil), RDF::DC.description, "\r"])
> g.dump(:ttl)
"\n<> <http://purl.org/dc/terms/description> \"\"\"\r\"\"\" .\n"
```

**Comment by escowles** [comment] 2015-01-23 15:40
So the issue isn't that this is generating an error (because the RDF isn't valid).  The issue is that it should be a 400 Bad Request error, right?

**Comment by awead** [comment] 2015-01-23 15:53
@escowles Just for some background, this test case originated from an object in our ScholarSphere repo that we're migrating to Fedora4. The user put in characters such as `\r\n` in the description field, which are stored in a NTriples datastream. When moving this to RDF in Fedora4, we're getting the LDP errors.

**Comment by escowles** [comment] 2015-01-23 15:57
@awead That makes sense, but I think there's some escaping issues with the example.  If I unescape it, I get:

```
<> <http://purl.org/dc/terms/description> """\r""" .
```

But I think if you want a literal that's just the carriage return, it should be:
```
<> <http://purl.org/dc/terms/description> "\r" .
```

**Comment by awead** [comment] 2015-01-23 15:59
@escowles this is the original ntriples datastream https://gist.github.com/awead/a87f9cb2bc9a6224ae54

**Comment by escowles** [comment] 2015-01-23 16:20
@awead I took your sample ruby code, and I think there is a bug in the escaping of the quotes.  Because it's producing `"""^M"""` when it should be producing `"^M"`.

**Comment by jcoyne** [comment] 2015-01-23 16:21
@escowles It's legal to delimit literals with `"""` see http://www.w3.org/TR/turtle/#h4_turtle-literals

**Comment by jcoyne** [comment] 2015-01-23 16:22
@escowles Also:
> Literals delimited by ", may not contain the characters ", LF, or CR.

**Comment by escowles** [comment] 2015-01-23 16:40
@jcoyne Hmm, I hadn't seen `"""`-delimited literals before, but the spec does say they're valid, and can contain newlines, carriage returns, etc.  So that `"""^M"""` output is valid.

So this looks like a problem either with Jena not accepting it (unlikely) or with how fcrepo4 is handling it.  I've created a JIRA ticket for this: https://jira.duraspace.org/browse/FCREPO-1299

**Comment by awoods** [comment] 2015-01-23 16:48
Tracking in JIRA: https://jira.duraspace.org/browse/FCREPO-1299

**Closed by awoods** 2015-01-23 16:48 UTC
