### ISSUE TITLE
NullPointerException when updating fcr:metadata with HTTP PUT

### ISSUE THREAD

**Issue by adolski** [fcrepo4/fcrepo4#819] opened 2015-06-23 16:23 UTC
I am regrettably not able to reproduce this outside of an application I have that is triggering it, but within that, I can get it to happen 100% of the time, with Fedora 4.2. I thought I would report it anyway in case it rings any bells.

At this point, I've created a binary node, downloaded its fcr:metadata representation as Turtle, and added some triples to it. I have not modified any existing triples:

    @prefix dc: <http://purl.org/dc/terms/> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

    <> <http://kumquat.library.illinois.edu/bytestreamShape> <http://kumquat.library.illinois.edu/Bytestream/Shape/Original>;
       <http://kumquat.library.illinois.edu/bytestreamType> <http://kumquat.library.illinois.edu/Bytestream/Type/Master>;
       <http://kumquat.library.illinois.edu/hasParent> <http://localhost:8080/fedora/rest/97/6c/48/be/976c48be-2120-42e5-89ac-4727213986f4/a9/a9/a0/c1/a9a9a0c1-1c39-430e-9c80-2a11c6cbbcd0>;
       dc:MediaType "audio/aiff" .

    <http://localhost:8080/fedora/rest/97/6c/48/be/976c48be-2120-42e5-89ac-4727213986f4/a9/a9/a0/c1/a9a9a0c1-1c39-430e-9c80-2a11c6cbbcd0/ce/75/52/21/ce755221-bed2-4b88-9dfa-583f32a8b5e0> a <http://www.jcp.org/jcr/nt/1.0resource>,
         <http://www.jcp.org/jcr/nt/1.0base>,
         <http://www.jcp.org/jcr/mix/1.0mimeType>,
         <http://www.jcp.org/jcr/mix/1.0lastModified>,
         <http://fedora.info/definitions/v4/repository#Binary>,
         <http://fedora.info/definitions/v4/repository#Resource>,
         <http://www.jcp.org/jcr/mix/1.0created>,
         <http://www.jcp.org/jcr/mix/1.0referenceable>;
       <http://fedora.info/definitions/v4/repository#created> "2015-06-23T16:08:02.143Z"^^xsd:dateTime;
       <http://fedora.info/definitions/v4/repository#createdBy> "bypassAdmin";
       <http://fedora.info/definitions/v4/repository#digest> <urn:sha1:9c12900dbbb9933aad70bd5d29bfbe794111d74d>;
       <http://fedora.info/definitions/v4/repository#hasFixityService> <http://localhost:8080/fedora/rest/97/6c/48/be/976c48be-2120-42e5-89ac-4727213986f4/a9/a9/a0/c1/a9a9a0c1-1c39-430e-9c80-2a11c6cbbcd0/ce/75/52/21/ce755221-bed2-4b88-9dfa-583f32a8b5e0/fcr:fixity>;
       <http://fedora.info/definitions/v4/repository#lastModified> "2015-06-23T16:08:02.143Z"^^xsd:dateTime;
       <http://fedora.info/definitions/v4/repository#lastModifiedBy> "bypassAdmin";
       <http://fedora.info/definitions/v4/repository#mimeType> "application/x-www-form-urlencoded";
       <http://fedora.info/definitions/v4/repository#mixinTypes> "fedora:Binary";
       <http://fedora.info/definitions/v4/repository#primaryType> "nt:resource";
       <http://fedora.info/definitions/v4/repository#uuid> "2a9ee88a-b7ec-405d-8cca-1384b21baa4c";
       <http://www.iana.org/assignments/relation/describedby> <http://localhost:8080/fedora/rest/97/6c/48/be/976c48be-2120-42e5-89ac-4727213986f4/a9/a9/a0/c1/a9a9a0c1-1c39-430e-9c80-2a11c6cbbcd0/ce/75/52/21/ce755221-bed2-4b88-9dfa-583f32a8b5e0/fcr:metadata>;
       <http://www.loc.gov/premis/rdf/v1#hasOriginalName> "beep-piano.aif";
       <http://www.loc.gov/premis/rdf/v1#hasSize> "22310"^^xsd:long .

    <http://localhost:8080/fedora/rest/97/6c/48/be/976c48be-2120-42e5-89ac-4727213986f4/a9/a9/a0/c1/a9a9a0c1-1c39-430e-9c80-2a11c6cbbcd0/ce/75/52/21/ce755221-bed2-4b88-9dfa-583f32a8b5e0/fcr:metadata> a <http://www.w3.org/ns/ldp#RDFSource>,
         <http://www.jcp.org/jcr/nt/1.0file>,
         <http://www.jcp.org/jcr/nt/1.0hierarchyNode>,
         <http://www.jcp.org/jcr/nt/1.0base>,
         <http://www.jcp.org/jcr/mix/1.0created>,
         <http://fedora.info/definitions/v4/repository#NonRdfSourceDescription>,
         <http://fedora.info/definitions/v4/repository#Resource>,
         <http://www.jcp.org/jcr/mix/1.0lastModified>,
         <http://www.jcp.org/jcr/mix/1.0referenceable>;
       <http://fedora.info/definitions/v4/repository#created> "2015-06-23T16:08:02.143Z"^^xsd:dateTime;
       <http://fedora.info/definitions/v4/repository#createdBy> "bypassAdmin";
       <http://fedora.info/definitions/v4/repository#hasParent> <http://localhost:8080/fedora/rest/97/6c/48/be/976c48be-2120-42e5-89ac-4727213986f4/a9/a9/a0/c1/a9a9a0c1-1c39-430e-9c80-2a11c6cbbcd0>;
       <http://fedora.info/definitions/v4/repository#lastModified> "2015-06-23T16:08:02.304Z"^^xsd:dateTime;
       <http://fedora.info/definitions/v4/repository#lastModifiedBy> "bypassAdmin";
       <http://fedora.info/definitions/v4/repository#mixinTypes> "fedora:NonRdfSourceDescription",
         "fedora:Resource";
       <http://fedora.info/definitions/v4/repository#primaryType> "nt:file";
       <http://fedora.info/definitions/v4/repository#uuid> "c942bb0e-5e21-4f38-b153-5c753c69f18f";
       <http://fedora.info/definitions/v4/repository#writable> true;
       <http://www.iana.org/assignments/relation/describes> <http://localhost:8080/fedora/rest/97/6c/48/be/976c48be-2120-42e5-89ac-4727213986f4/a9/a9/a0/c1/a9a9a0c1-1c39-430e-9c80-2a11c6cbbcd0/ce/75/52/21/ce755221-bed2-4b88-9dfa-583f32a8b5e0> .

When I attempt tp PUT it back, the result is a 500 Internal Server Error:

    java.lang.NullPointerException
    	at org.modeshape.jcr.JcrMultiValueProperty.getValues(JcrMultiValueProperty.java:130)
    	at org.modeshape.jcr.JcrMultiValueProperty.getValues(JcrMultiValueProperty.java:48)
    	at org.fcrepo.kernel.impl.rdf.impl.mappings.PropertyValueIterator.computeNext(PropertyValueIterator.java:67)
    	at org.fcrepo.kernel.impl.rdf.impl.mappings.PropertyValueIterator.computeNext(PropertyValueIterator.java:35)
    	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
    	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
    	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
    	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
    	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
    	at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43)
    	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
    	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
    	at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43)
    	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:650)
    	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
    	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
    	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
    	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
    	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
    	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
    	at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43)
    	at org.fcrepo.kernel.utils.iterators.GraphDifferencingIterator.computeNext(GraphDifferencingIterator.java:84)
    	at org.fcrepo.kernel.utils.iterators.GraphDifferencingIterator.computeNext(GraphDifferencingIterator.java:37)
    	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
    	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
    	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
    	at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43)
    	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:650)
    	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
    	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
    	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
    	at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43)
    	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
    	at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43)
    	at org.fcrepo.kernel.impl.utils.iterators.PersistingRdfStreamConsumer.consume(PersistingRdfStreamConsumer.java:107)
    	at org.fcrepo.kernel.impl.FedoraResourceImpl.replaceProperties(FedoraResourceImpl.java:475)
    	at org.fcrepo.http.api.ContentExposingResource.replaceResourceWithStream(ContentExposingResource.java:598)
    	at org.fcrepo.http.api.FedoraLdp.createOrReplaceObjectRdf(FedoraLdp.java:282)
    	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
    	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
    	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
    	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
    	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
    	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
    	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
    	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
    	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
    	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
    	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
    	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
    	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
    	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
    	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
    	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
    	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    	at org.eclipse.jetty.server.Server.handle(Server.java:497)
    	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
    	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by acoburn** [comment] 2016-10-07 00:21
@adolski is this issue still relevant with version 4.6.0 of Fedora?

**Comment by adolski** [comment] 2016-10-07 15:02
@acoburn I'm sorry, I can't reproduce this.

**Comment by acoburn** [comment] 2016-10-07 16:06
@adolski thanks for checking. I will close this issue as "Cannot reproduce", but if it crops up again, feel free to either reopen this issue or create a new ticket.

**Closed by acoburn** 2016-10-07 16:06 UTC
